version: '3.7'

services:
  web:
    container_name: fastapi-role-based-access-control-auth-service
    build: .
    environment:
      - PYTHONPATH=${PYTHONPATH}
    volumes:
      - .:/app
    command: /app/bash_commands/startup.sh
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
  
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      #- ./bash_commands/create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/init-database.sh
    environment:
      #- POSTGRES_MULTIPLE_DATABASES=${TEST_DB_NAME},${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}

volumes:
  postgres_data: